In [1]:
import pandas as pd
import numpy as np
from sklearn.datasets import make_regression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error

In [21]:
class MultipleRidgeRegression:
    """
    Implements Multiple Ridge Regression using NumPy.

    This class provides methods to fit a multiple ridge regression model
    to training data and make predictions on new data. It calculates the
    coefficients and intercept using the closed-form solution (Normal Equation).
    """
    def __init__(self,alpha = 0.1):
        """
        Initializes the MultipleLinearRegression model.

        Attributes:
            coef_ (np.ndarray): The learned coefficients for the features.
            intercept_ (float): The learned intercept (bias) term.
            alpha: The regularisation term.
        """
        self.alpha = alpha
        self.coef_ = None
        self.intercept_ = None

    def fit(self,X_train:np.ndarray,y_train:np.ndarray):
        """
        Fits the multiple ridge regression model to the training data.

        The coefficients and intercept are calculated using the Normal Equation:
        betas = (X_train.T @ X_train)^-1 @ X_train.T @ y_train

        Args:
            X_train (np.ndarray): Training feature data. Can be 1D or 2D.
                                  If 1D, it will be reshaped to 2D.
            y_train (np.ndarray): Training target values.
        """
         # Ensure that the array is 2D even if the array is 1D
        if X_train.ndim == 1:
            X_train = X_train.reshape(-1, 1)
        # Add a column of ones to X_train for the intercept term
        X_train = np.insert(X_train,0,1,axis = 1)
        # Add the identity matrix
        I = np.identity(X_train.shape[1])
        # Set the first row and column's value to zero.
        I[0][0] = 0
        
        
        # Calculate betas (coefficients and intercept) using the Normal Equation
        # np.linalg.inv: computes the inverse of a matrix
        # np.dot: performs dot product of two arrays
        betas = np.linalg.inv(np.dot(X_train.T,X_train) + self.alpha * I).dot(X_train.T).dot(y_train)
        
        # get the intercept from the matrix
        self.intercept_ = betas[0] 
        self.coef_ = betas[1:]

    def predict(self,X_test:np.ndarray) -> np.ndarray:
        """
        Predicts target values for new data using the trained model.

        Args:
            X_test (np.ndarray): Feature data for making predictions. Can be 1D or 2D.
                                 If 1D, it will be reshaped to 2D.

        Returns:
            np.ndarray: Predicted target values.
        """
        is_1D = False 
        if X_test.ndim == 1:
            X_test = X_test.reshape(-1,1)
            # Set the flag to True if the input array is 1D
            is_1D = True 
        if self.coef_.ndim == 1:
            self.coef_ = self.coef_.reshape(-1,1)
        y_pred = np.dot(X_test,self.coef_) + self.intercept_
        if is_1D:
            # Flatten the array so as to match the original array
            y_pred = y_pred.flatten() 
        return y_pred 
        

In [2]:
# Declare frequently used variables
random_state = 42
test_size = 0.2

In [22]:
# Create the Regression model
multipleLinearRegressor = MultipleRidgeRegression(alpha=0)

In [8]:
# Generate a synthetic regression dataset using make_regression

X,y = make_regression(n_samples=500,n_features=10,noise=5,random_state=42)

In [9]:
print(f"Shape of  X:{X.shape} Shape of y:{y.shape}")

Shape of  X:(500, 10) Shape of y:(500,)


In [10]:
print(f"First five rows of X:\n{X[:5]}")

First five rows of X:
[[ 1.02406253  2.06150358  2.55819929 -0.5642476   1.54210995 -0.55185815
   1.20836623  2.00609289  0.59252695  0.1845513 ]
 [-0.63773998  0.28916864  0.67481949 -1.12272202  0.16645221 -0.04946371
   2.45530014  0.49245126 -0.53099696  0.38240975]
 [ 0.779349   -0.84685097  0.75749515  1.37053614  0.28375102 -1.05014074
   1.24961891 -0.98787334 -0.03901952  0.6952029 ]
 [ 0.51390785 -1.00033132 -0.47490366  0.8712973   0.12637958  0.5866938
  -0.67774497  1.938929    0.17958178 -1.34597968]
 [-0.18315047  0.81550102 -0.21345678  0.49619919  0.51149958 -0.32701732
  -0.04808851  1.93515404 -0.35667313 -0.53531671]]


In [11]:
print(f"First five rows of y:\n{y[:5]}")

First five rows of y:
[461.48023648 197.27380175 104.50062488  32.5510921  172.99119757]


In [12]:
# Split the dataset into training and spliting data
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=test_size,random_state=random_state)

In [23]:
# Train the model
multipleLinearRegressor.fit(X_train,y_train)

In [24]:
# Make predictions on the test set
y_pred = multipleLinearRegressor.predict(X_test)

In [25]:
print("----- Model's Attributes ----")
print(f"Learned Coefficients:\n {multipleLinearRegressor.coef_}")
print(f"Learned Intercept: {multipleLinearRegressor.intercept_}")

----- Model's Attributes ----
Learned Coefficients:
 [[41.84246733]
 [64.67596171]
 [18.90879487]
 [46.43722569]
 [24.40337682]
 [16.66576896]
 [82.61928291]
 [64.40068559]
 [ 7.44944906]
 [28.70063419]]
Learned Intercept: -0.15415337973213994


In [26]:
# Evaluate the model's performance
print("===== Performance on make_regression dataset =====")
print(f"R2 Score: {r2_score(y_test, y_pred)}")
print(f"Mean Absolute Error (MAE): {mean_absolute_error(y_test, y_pred)}")
print(f"Mean Squared Error (MSE): {mean_squared_error(y_test, y_pred)}")

===== Performance on make_regression dataset =====
R2 Score: 0.9987683064510353
Mean Absolute Error (MAE): 3.8989382988775367
Mean Squared Error (MSE): 24.274794379788503


In [27]:
# Generate a 1D synthetic regression dataset
X_1d, y_1d = make_regression(n_samples=100,n_features=1,noise=5,random_state=42)

In [28]:
print(f"Shape of  X:{X_1d.shape} Shape of y:{y_1d.shape}")

Shape of  X:(100, 1) Shape of y:(100,)


In [29]:
print(f"First five rows of X:\n{X_1d[:5]}")

First five rows of X:
[[ 0.93128012]
 [ 0.08704707]
 [-1.05771093]
 [ 0.31424733]
 [-0.47917424]]


In [30]:
print(f"First five rows of y:\n{y_1d[:5]}")

First five rows of y:
[ 44.82629315  -3.21591488 -39.53420495  11.82188621 -18.86981858]


In [31]:
X_tr,X_ts,y_tr,y_ts = train_test_split(X_1d,y_1d,test_size=test_size,random_state=random_state)

In [32]:
multipleLinearRegressor.fit(X_tr,y_tr)

In [33]:
# Make predictions on the test set
y_pd = multipleLinearRegressor.predict(X_ts)

In [34]:
print("----- Model's Attributes ----")
print(f"Learned Coefficients: {multipleLinearRegressor.coef_}")
print(f"Learned Intercept: {multipleLinearRegressor.intercept_}")

----- Model's Attributes ----
Learned Coefficients: [[42.99264124]]
Learned Intercept: 0.04961110711293992


In [35]:
# Evaluate the model's performance
print("===== Performance on make_regression dataset =====")
print(f"R2 Score: {r2_score(y_pd,y_ts)}")
print(f"Mean Absolute Error (MAE): {mean_absolute_error(y_pd,y_ts)}")
print(f"Mean Squared Error (MSE): {mean_squared_error(y_pd,y_ts)}")

===== Performance on make_regression dataset =====
R2 Score: 0.9823633330986319
Mean Absolute Error (MAE): 4.208329961104525
Mean Squared Error (MSE): 26.05055663296755
